# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: pipeline-template
      type: git
      name: "Study Definitions Repository/pipeline-template"


name: $(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)

stages:
  - stage: Build
    jobs:
      - job: build_job
        # variables:
        #   - group: DEV
      - template: dotnet-main.yml@pipeline-template
        parameters:
          run_ci: 'true'
          run_sonar: $(Sonar)
  
  - stage: deploy_dev
    displayName: Deploy Dev Stage
    dependsOn: Build
    jobs:
      - deployment: Deploy
        variables:
          - group: DEV
        displayName: Deploy Dev
        environment: api-dev
        strategy:
         runOnce:
           deploy:
             steps:
               - task: FileTransform@1
                 displayName: 'File Transform:'
                 inputs:
                   fileType: json
                   folderPath: '$(Agent.BuildDirectory)\Build-Artifact\publish.zip'
                   targetFiles: '**/appsettings.json'
                

                
               - task: AzureWebApp@1
                 inputs:
                    azureSubscription: 'sc_spn_sdr_cicd'
                    appType: 'webApp'
                    appName: 'apps-sdr-dev2-eastus-002'
                    package: '$(Agent.BuildDirectory)/Build-Artifact/publish.zip'
                    deploymentMethod: 'auto'


  
  - stage: deploy_qa
    displayName: Deploy QA Stage
    dependsOn: Build
    jobs:
      - deployment: Deploy
        variables:
          - group: QA
        displayName: Deploy QA
        environment: api-qa
        strategy:
         runOnce:
           deploy:
             steps:
               - task: FileTransform@1
                 displayName: 'File Transform:'
                 inputs:
                   fileType: json
                   folderPath: '$(Agent.BuildDirectory)\Build-Artifact\publish.zip'
                   targetFiles: '**/appsettings.json'
                

                
               - task: AzureWebApp@1
                 inputs:
                    azureSubscription: 'sc_spn_sdr_cicd'
                    appType: 'webApp'
                    appName: 'apps-sdr-qa-eastus-002'
                    package: '$(Agent.BuildDirectory)/Build-Artifact/publish.zip'
                    deploymentMethod: 'auto'
               
