jobs:

- job: Set_Build_Parameter
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      echo "This is job Set_Build_Parameter."
      echo "vso[task.setvariable variable=setBuildTypeCI;isOutput=true]${{ parameters.run_ci }}"
    name: StageType


- job: JOB_CI
  dependsOn: Set_Build_Parameter
  pool: 
    vmImage: 'windows-2019'
  condition: eq(variables['JOB_CI'], 'true')
  workspace:
    clean: all
  steps:
  - template: SDR-CI/dotnet-ci.yml


- job: JOB_Sonar
  dependsOn: Set_Build_Parameter
  pool: 
    vmImage: 'windows-2019'
  condition: eq(variables['JOB_Sonar'], 'true')
  workspace:
    clean: all
  steps:
  - template: SDR-CI/dotnet-sonar.yml